version: '3.7'

services:
  standalone:
    image: apachepulsar/pulsar:2.7.0
    ports:
      - "8181:8080"
      - "6650:6650"
    volumes:
      - $HOME/volume/pulsar/data:/pulsar/data
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone --advertised-address 127.0.0.1"
  dashboard:
    image: apachepulsar/pulsar-dashboard:2.7.0
    depends_on:
      - standalone
    ports:
      - "9090:80"
    environment:
      - SERVICE_URL=http://standalone:8080
