version: '3.7'

services:
  dd-agent:
    image: gcr.io/datadoghq/agent:7
    ports:
      - "8181:8080"
    volumes:
    - /proc/:/host/proc/:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
    - DD_API_KEY=$DATADOG_API_KEY
    - DD_SITE=datadoghq.eu