version: '3.7'

services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - PGDATA=$HOME/postgresql/data
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data