version: '3.8'

services:

  vault:
    build:
      context: ../../apps/vault
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    volumes:
      - ../../apps/vault/config:/vault/config
      - ../../apps/vault/policies:/vault/policies
      - ../../apps/vault/data:/vault/data
      - ../../apps/vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    command: server -config=../../apps/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
